### ISSUE TITLE
Transfer ownership of the SACRO viewer to the UWE team

### ISSUE THREAD

**Issue by benbc** [AI-SDC/SACRO-Viewer#246]
We'd like to transfer ownership of the viewer to the UWE team so that they can manage its future maintenance.

Three things to do here:

1. [x] Rename the repo "SACRO Viewer", because that will make more sense in its new home.
2. [x] Transfer ownership into the [AI-SDC](https://github.com/AI-SDC) organization.
3. [x] Sort out any repo membership/ownership concerns.
4. [x] Decide what will happen to the download URLs.

We should work with Jim Smith to make sure this all goes smoothly.

**Comment by bloodearnest** [comment]
This is done.
