### ISSUE TITLE
Unable to download .msi file for Windows

### ISSUE THREAD

**Issue by dusan-ilic-mhra** [AI-SDC/SACRO-Viewer#263]
Hi, 

When I clicked here:

![image](https://github.com/user-attachments/assets/d85700cd-9c1e-4f1b-9100-fcf286d05fe7)

I was unable to download .msi file for Windows:

![image](https://github.com/user-attachments/assets/4fa3b298-baa1-46b9-8b49-b641853a6e83)

How can I download it?

**Comment by jim-smith** [comment]
@dusan-ilic-mhra thanks for the heads up - looks like the nightly build did not happen for some reason.  I'll get someone to look at it asap.

**Comment by dusan-ilic-mhra** [comment]
Thanks, @jim-smith. Please send me an update when it's done.

**Comment by jim-smith** [comment]
@dusan-ilic-mhra can you check now please

**Comment by dusan-ilic-mhra** [comment]
@jim-smith I successfully download it. Thank you.

**Comment by jim-smith** [comment]
@dusan-ilic-mhra great. If you could let mew know when it is working I  will close the issue.    Happy to be online if you want to talk it through (off tomorrow but available weds-fi)

**Comment by dusan-ilic-mhra** [comment]
Thank you @jim-smith. You can close the issue.
